CREATE EVENT AutoDeleteOldConcerts
    ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY
    ON COMPLETION PRESERVE
    DO
    DELETE LOW_PRIORITY FROM db_telegrambot.concerts c WHERE c.date < CURRENT_DATE